#*** Traffic Classification Policy for nmeta
#*** Written in YAML
#
'PolicyRule 0':
    comment: OpenFlow Protocol Traffic
    match_type: any
    policy_conditions:
        tcp_src: 6633
        tcp_dst: 6633
    actions:
        set_qos_tag: QoS_treatment=system_priority
        set_desc_tag: description="OpenFlow Protocol Traffic"
'PolicyRule 1':
    comment: Test of IP ranges and netmasks - High Priority Business Traffic
    match_type: all
    policy_conditions:
        ip_src: 192.168.56.10-192.168.56.18
        ip_dst: 192.168.57.40
    actions:
        set_qos_tag: QoS_treatment=high_priority
        set_desc_tag: description="High Priority Business Traffic A->B"
'PolicyRule 2':
    comment: Test of IP ranges and netmasks - High Priority Business Traffic
    match_type: all
    policy_conditions:
        ip_src: 192.168.57.40
        ip_dst: 192.168.56.10-192.168.56.18
    actions:
        set_qos_tag: QoS_treatment=high_priority
        set_desc_tag: description="High Priority Business Traffic A<-B"  
'PolicyRule 3':
    comment: SSH traffic
    match_type: any
    policy_conditions:
        tcp_src: 22
        tcp_dst: 22
    actions:
        set_qos_tag: QoS_treatment=high_priority
        set_desc_tag: description="High Priority SSH Traffic"

