#*** Example Identity Main Policy
#*** Written in YAML
#
tc_rules:
    # Traffic Classification Rulesets and Rules
    tc_ruleset_1:
        - comment: OpenFlow Protocol Traffic
          match_type: any
          conditions_list:
              - match_type: any
                tcp_src: 6633
                tcp_dst: 6633
          actions:
              set_qos_tag: QoS_treatment=system_priority
              set_desc_tag: description="OpenFlow Protocol Traffic"
        - comment: Explicitly set Iperf traffic to default class
          match_type: any
          conditions_list:
              - match_type: any
                tcp_src: 5001
                tcp_dst: 5001
          actions:
              set_qos_tag: QoS_treatment=default_priority
              set_desc_tag: description="Default Priority Iperf Traffic"  
        - comment: SSH traffic
          match_type: any
          conditions_list:
              - match_type: any
                tcp_src: 22
                tcp_dst: 22
          actions:
              set_qos_tag: QoS_treatment=high_priority
              set_desc_tag: description="High Priority SSH Traffic"
        - comment: Use Case Identity-2 - High Priority Business Traffic
          match_type: any
          conditions_list:
              - match_type: any
                identity_lldp_systemname_re: '.*\.dev\.example\.com'
          actions:
              set_qos_tag: QoS_treatment=high_priority
              set_desc_tag: description="High Priority Business Traffic" 

